apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: sig-data
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-nodeport
  namespace: sig-data
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30087
