apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sig-data-kustomize
  namespace: argocd
  labels:
    app: sig-data
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/sig-data.git  # Update this to your repo
    targetRevision: main
    path: argocd
    kustomize:
      images:
        - sig-data:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: sig-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10